### ISSUE TITLE
Add soical image for contributors profile page

### ISSUE THREAD

**Issue by bodhish** [coronasafe/leaderboard#127]
It would have been nice if we had an og:image that show the image and name of the contributor;

![image](https://github.com/coronasafe/leaderboard/assets/14979190/bbeae786-6ec7-4a19-ad04-6fb00c7f77c9)

example: 
![image](https://github.com/coronasafe/leaderboard/assets/14979190/2d822bbc-87bb-4de3-bd03-1ae30975264e)

**Comment by dgparmar14** [comment]
![image](https://github.com/coronasafe/leaderboard/assets/99136186/2197d331-bd5b-4abb-bd1f-6b20d39a171c)

How can I add an og image to this? I mean there are below name slack, GitHub, LinkedIn, and twitter links. So how to attache that in og image with a link?

**Comment by rithviknishad** [comment]
It can be something simple as like this:

Title could be `{ contributor name } - Contributor at Open Healthcare Network`
The description could be the short bio of the user

Image could be the github image itself, and maybe we could show the number of contributions made so far?

<img width="589" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/98f4e832-4b21-4b62-bb84-1a5b5e7e378f">

**Comment by dgparmar14** [comment]
I have to change in contributors page? or somewhere else?

**Comment by rithviknishad** [comment]
Yup, contirbutor profile page

**Comment by dgparmar14** [comment]
In contributors page where should I change this ???
I can't get it

**Comment by rithviknishad** [comment]
Refer nextjs docs

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image
https://nextjs.org/docs/app/api-reference/functions/generate-metadata

**Comment by rithviknishad** [comment]
No changes in the site UI required

**Comment by dgparmar14** [comment]
> It can be something simple as like this:
> 
> Title could be `{ contributor name } - Contributor at Open Healthcare Network`
> The description could be the short bio of the user
> 
> Image could be the github image itself, and maybe we could show the number of contributions made so far?
> 
> <img width="589" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/98f4e832-4b21-4b62-bb84-1a5b5e7e378f">
> 

So,Where this is shown ?Can you explain more 🤔

**Comment by Ashesh3** [comment]
@dgparmar14 The issue is not about making any UI changes, I think you are confusing the addition of open graph meta tags with actually making changes in the UI. When an external website is trying to fetch a thumbnail of any of our contributors' profile, in that case we can add a special http meta tag which will guide the site which image to use as the thumbnail.
Refer to the resources provided by @rithviknishad above.

https://nextjs.org/learn/dashboard-app/adding-metadata (Refer to Open Graph Metadata section)

This is different from actually changing the image in the UI itself, the issue is about adding that meta tag and not any changes to the actual image displayed on the page.

**Comment by dgparmar14** [comment]
@rithviknishad @Ashesh3 Okk, Properly understood I don't think about this because in the leaderboard we are using og images to show posts. So I was confused, Now i get it and I will come up with a solution. Thanks...

**Comment by dgparmar14** [comment]
It is something like this?
![Screenshot 2024-03-12 160749](https://github.com/coronasafe/leaderboard/assets/99136186/cb1419ac-6b99-4a09-b6dc-16d8e8e88f40)

I built the above by creating a new file. Can you please verify this or provide any suggestions ?
 
![image](https://github.com/coronasafe/leaderboard/assets/99136186/d8d2766b-7406-4b17-ab89-95171c4b872d)

**Comment by rithviknishad** [comment]
The title and description need not be part of the image. Those can be part of the page's title and description instead. Refer: https://nextjs.org/docs/app/api-reference/functions/generate-metadata


The image element could contain the contributors' image from GitHub and a highlight of contributions as we have on their profile page... It could be shown differently and need not be exactly how the screenshot below is.

<img width="953" alt="image" src="https://github.com/coronasafe/leaderboard/assets/25143503/ecb6b555-c3c0-4514-a2df-d384f7521207">

**Comment by dgparmar14** [comment]
![Screenshot 2024-03-16 160451](https://github.com/coronasafe/leaderboard/assets/99136186/3b8e679d-7fdf-4d56-a823-c2949c53e744)


How it looks any suggetion?

**Comment by rithviknishad** [comment]
This does not look nice. The logo looks stretched and the colors feel too strong. It’s hard to see the icons as there is not enough contrast.

Let’s keep it simple. Place the org logo (the same that is used in the footer without a bg-colour) without stretching, and the contributor highlights with secondary/primary colour. No need to make it colourful.

**Comment by dgparmar14** [comment]
![image](https://github.com/coronasafe/leaderboard/assets/99136186/68710677-4d9f-430c-ad68-176da5a06592)

How it looks?
Regarding the logo, it appears black because when I use the`'logo. webp'` from the public directory, it's in white text. However, our OG image background is white, making it difficult to see. For the OG image, a white background is more suitable. Additionally, the leaderboard is a tool that will be used by other organizations, so each organization may prefer their logo. Therefore, I thought it best to use the same logo as found on the internet.

If there any suggestion regarding styling or addition?
