### ISSUE TITLE
Add Twitter to Connect 

### ISSUE THREAD

**Issue by Indrajeety993648** [coronasafe/leaderboard#480]
### What I expected to happen
I expected to see a Twitter icon in the "Connect" section of the website footer, allowing users to connect with the organization via Twitter.

### Our reason
Adding a Twitter icon/link would enhance the visibility of the organization's social media presence and provide an additional platform for users to stay updated and engage with the organization's content.

### What I plan to do 
1. Add a Twitter icon alongside the existing icons in the "Connect" section.
2. Link the icon to the organization's official Twitter profile.
3. Ensure the icon design matches the style of the existing icons for consistency.

## current Connect Section 
![Screenshot from 2024-08-06 19-56-40](https://github.com/user-attachments/assets/bb5dde84-7905-4721-9ac7-766928507c38)

**Comment by Indrajeety993648** [comment]
@rithviknishad  please assign this issue to me.

**Comment by Indrajeety993648** [comment]
@khavinshankar  please review & assign this issue to me .

**Comment by Indrajeety993648** [comment]
@rithviknishad    

Could you please provide me with the Twitter URL for our company? I would like to update it in our footer component to ensure it reflects the correct information.

**Comment by rithviknishad** [comment]
@Indrajeety993648 

Not all orgs may have the required all social accounts. So let's show the social logo's only if that social's env value is defined. 

So

1. Make the social env's optional (even existing ones). 
2. Add X logo (the new one, not twitter), if the env value is present.
3. You may skip adding the twitter URL for this org.

**Comment by Indrajeety993648** [comment]
@rithviknishad   Thank you for clarifying the issue.

**Comment by Indrajeety993648** [comment]
@rithviknishad    I am unable to understand your point clearly. There is no Twitter_Url in the .env file, and you mentioned that if the link is not present, I should make it optional and not render the page. Additionally, there is no Twitter icon in the footer section, so I added a Twitter icon that does not render anywhere, as per your earlier instructions.

Could you please explain the problem in more detail so I can better understand it? I did my best to resolve the issue based on my understanding, but if you could clarify the feature you're requesting, it would greatly help me to address the issue correctly.

**Comment by rithviknishad** [comment]
So, leaderboard is deployed by different organisations right to showcase their teams and contributors contributions. However, each org. would have a different set of social medias. Some may have twitter, some may not. Some may have youtube, some may not. And so on...


So, you've to define those env's in the env. schema here: https://github.com/coronasafe/leaderboard/blob/main/env.mjs

So that even if it is not defined in the `.env` file, it'd be treated as an optional field.

Now in the footer section, you'll have to check if the particular env. is defined or not. Leaderboard should support showing each of the supported social media's if that corresponding env. value is defined.

**Comment by Indrajeety993648** [comment]
@rithviknishad  thank You for  clarification , I'll work on according to that
