### ISSUE TITLE
Bug: Timeline of contribution is not proper

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/leaderboard#97]
https://contributors.ohc.network/contributors/sainak

The last 5 entries here at the bottom are from June.

Above that, we see updates from May. Above that again June and then July and the more recent months according to the timeline.

The timeline must start with May at the bottom and then have June above that.

**Comment by Ritesh-Aggarwal** [comment]
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/57039447/197740551-600d067e-d7ee-4879-a38b-682325990807.png">

currently the contibutions are shown in the following manner:
- github contributions (new to old)
- slack messages (old to new)

@aparnacoronasafe 
There is some issue in entries from may 11 to may 22 apart from that,
I think it is supposed to be that way so that user can start looking at slack messages from bottom and github's from top. 
Should I change the behaviour anyway?

**Comment by rithviknishad** [comment]
A very big page is rendered nowadays since we have lots of data, so how about we introduce:

- A tab (I vote for this) or filters to filter out event sources: [GitHub, Slack].
- And also pagination or month-based filter similar to a style of pagination?

cc: @bodhish what do you think about this?
